@url = http://localhost:8888
@json = Content-Type: application/json

###
get {{url}}/users/

###
post {{url}}/users/create
{{json}}
 

{
  "username": "yo",
  "sex": "女",
  "phone": "1735547393",
  "type": "管理员",
  "password": "8888",
}

###
get {{url}}/users/profile
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDRlYzdjMmI4YTIyMmI4ODQ4N2M5OSIsImlhdCI6MTYxNTIyMDUxN30.W89Y5ViVtEk2MI7O94bnjzDC_8UJDiKZpeEhnZxx5dw

###
post {{url}}/categorys/add
{
  "name": "消毒水",
  "code": "02",
  "description": "ddd"
}